# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  # the name of the service connection that you created above
  serviceConnectionToAzure: azurerm-sc
  # the name of your web app here is the same one you used above
  # when you created the web app using the Azure CLI
  appName: my-app-name-func-15feb
  # the name of your functionApp is what you provided as
  # stagingDirectory in pom.xml
  functionAppName: 'javafunctions'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)/target/azure-functions/$(functionAppName)/'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(build.artifactstagingdirectory)'
    artifact: 'drop'
    publishLocation: 'pipeline'

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'azurerm-sc'
    appType: 'functionApp'
    appName: '$(appName)'
    package: '$(system.defaultworkingdirectory)/target/azure-functions/$(functionAppName)/*.jar'
